### ISSUE TITLE
Not working on Ionic/Capacitor project - Is there an example project? 

### ISSUE THREAD

**Issue by davicedraz** [oracle/pushiomanager-cordova-plugin#1]
I followed the documentation to the letter and was unable to make it work in my Ionic application.

On README.md, an example application is referenced, but the [link](https://github.com/oracle/pushiomanager-cordova-plugin#sample-app) is empty.

Also, i have added cordova-plugin-pushiomanager plugin to my Capacitor project, but the project is unable to compile, returning the following error:

```
Failed to resolve:: PushIOManager-6.47.1:
Affected Modules: app, capacitor-cordova-android-plugins
```

**Comment by neerhaj** [comment]
@davicedraz There was a version mismatch in the Android gradle file. Please try again.
