### ISSUE TITLE
Not finding Google Play services even on emulators and devices with Google Play services is installed

### ISSUE THREAD

**Issue by dan-olsn** [oracle/pushiomanager-cordova-plugin#5]
Having trouble getting the Pushio Manager to register the app on Android because of the below error where it can not find Google Play services. 

D/PluginManager: init()
V/pushio-cordova: Initializing plugin
I/pushio: Push IO Manager - 6.47
**E/pushio: PIORegM dNS Google Play services library not found.
E/pushio: PIORegM dNS This library is a required dependency as of PushIO SDK 2.11.0**
W/pushio: PIORegM dNS Google Play services not found. Trying ADM.
W/pushio: PIORegM dNS ADM not found.
W/pushio: PIORegM dNS Device supports no known notification services.

Have the plugin installed in a project with the following settings:

Cordova CLI 10.0.0
Cordova Android 9.0.0
Android SDK Tools 30.0.3

minSdkVersion 22
targetSdkVersion 29

Have tested on:
Nexus 5X SDK 27
Pixel 4 SDK 30

**Comment by neerhaj** [comment]
Please try adding the following dependency in `android/app/build.gradle`

`implementation 'com.google.firebase:firebase-messaging:17.3.0' `
